### ISSUE TITLE
Add functions to core.py

### ISSUE THREAD

**Issue by anotherjoshsmith** [jayruth/NovoNordisk_Capstone#18]
We have discussed several functions that should be added to `core.py` to provide users a means to predict experimental observables from amino acid sequence or nucleotide sequence. The following functions need to be added:

- [ ] encode sequence
- [ ] assign classes for input y
- [ ] train C-LSTM model
- [ ] predict with previously trained C-LSTM model

Many of these functions can be written by refactoring the code in `archive/josh/LSTM.ipynb`. Let's do ittttt!!!!!

**Comment by jayruth** [comment]
This is all done now
